name: Deploy to Azure VMSS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SSH script on VMSS instance1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VMSS_HOST }}
          port: ${{ secrets.VMSS_PORT }}
          username: ${{ secrets.VMSS_USER }}
          password: ${{ secrets.VMSS_PASSWORD }}
          script: |
            cd /var/www/html
            sudo git pull origin main
            sudo systemctl restart apache2